# Generated by Django 6.0.4 on 2026-04-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMMUNAL", "Komunal"),
                            ("RAW", "Hom ashyo"),
                            ("EXTERNAL", "Tashqi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sub_category", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OFFLINE", "Offline"),
                            ("ONLINE", "Online"),
                            ("EXTRA", "Extra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
