# Generated by Django 6.0.4 on 2026-04-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
    ]
