# Generated by Django 6.0.4 on 2026-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owner", "0002_remove_income_owner_delete_expense_delete_income"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("light", "Engil avtomobil"),
                            ("heavy", "Og'ir transport"),
                            ("polish", "Polishing"),
                            ("interior", "Salon tozalash"),
                            ("full", "To'liq kompleks"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Xizmat turi",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="Minimal narx (so'm)",
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="Maksimal narx (so'm)",
                    ),
                ),
                (
                    "recommended_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Tavsiya etilgan narx",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Narx ro'yxati",
                "verbose_name_plural": "Narx ro'yxatlari",
                "ordering": ["service_type"],
            },
        ),
    ]
