# Generated by Django 6.0.4 on 2026-04-15 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("worker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Buyum nomi")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="bonuses/", verbose_name="Rasm"
                    ),
                ),
                (
                    "token_cost",
                    models.PositiveIntegerField(verbose_name="Narxi (tanga)"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Miqdori"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bonus",
                "verbose_name_plural": "Bonuslar",
                "ordering": ["token_cost"],
            },
        ),
        migrations.CreateModel(
            name="BonusClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bonus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="core.bonus",
                        verbose_name="Bonus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claimed_bonuses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Olingan bonus",
                "verbose_name_plural": "Olingan bonuslar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tangalar soni"
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jami yig'ilgan"
                    ),
                ),
                (
                    "total_spent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jami sarflangan"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sodiqlik tangasi",
                "verbose_name_plural": "Sodiqlik tangalari",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("accepted", "Qabul qilindi"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Yakunlandi"),
                            ("rejected", "Rad etildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Mijoz izohi"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Narx (so'm)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="customer.car",
                        verbose_name="Mashina",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "service_ad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="worker.servicead",
                        verbose_name="Xizmat e'loni",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        limit_choices_to={"role": "worker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ishchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[("earn", "Yig'ildi"), ("spend", "Sarflandi")],
                        max_length=10,
                        verbose_name="Turi",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Miqdor")),
                ("description", models.CharField(max_length=200, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loyalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.loyaltytoken",
                        verbose_name="Hisob",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.order",
                        verbose_name="Buyurtma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tanga tranzaksiyasi",
                "verbose_name_plural": "Tanga tranzaksiyalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Yulduz (1-5)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="core.order",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Baholovchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baho",
                "verbose_name_plural": "Baholar",
                "ordering": ["-created_at"],
            },
        ),
    ]
