# Generated by Django 6.0.4 on 2026-04-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("new_order", "Yangi buyurtma"),
                            ("order_accept", "Buyurtma qabul qilindi"),
                            ("order_reject", "Buyurtma rad etildi"),
                            ("order_done", "Buyurtma yakunlandi"),
                            ("new_worker", "Yangi ishchi so'rovi"),
                            ("worker_approved", "Ishchi tasdiqlandi"),
                            ("bonus_claimed", "Bonus olindi"),
                        ],
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Sarlavha")),
                ("message", models.TextField(verbose_name="Xabar")),
                ("icon", models.CharField(default="fa-bell", max_length=50)),
                ("color", models.CharField(default="cyan", max_length=20)),
                ("url", models.CharField(blank=True, default="#", max_length=200)),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma",
                "verbose_name_plural": "Bildirishnomalar",
                "ordering": ["-created_at"],
            },
        ),
    ]
