# Generated by Django 6.0.4 on 2026-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Buyurtma vaqti"
            ),
        ),
    ]
