# Generated by Django 6.0.4 on 2026-05-04 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_order_scheduled_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(default="Oltiariq", max_length=100)),
                ("date", models.DateField()),
                (
                    "rain_probability",
                    models.PositiveSmallIntegerField(
                        help_text="Yomg'ir yog'ish ehtimoli foizda",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ob-havo",
                "verbose_name_plural": "Ob-havo ma'lumotlari",
                "unique_together": {("city", "date")},
            },
        ),
    ]
