# Generated by Django 6.0.4 on 2026-06-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('card', 'Bank kartasi'), ('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd pul')], default='card', max_length=10, verbose_name="To'lov usuli")),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Karta oxirgi 4')),
                ('holder_name', models.CharField(blank=True, max_length=80, verbose_name='Karta egasi')),
                ('transaction_id', models.CharField(max_length=24, unique=True, verbose_name='Tranzaksiya ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='core.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Chek',
                'verbose_name_plural': 'Cheklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
