# Generated by Django 6.0.4 on 2026-06-10 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user_request', "Foydalanuvchi so'rovi"), ('auto_inactive', 'Avtomatik (faolsizlik)')], default='user_request', max_length=20, verbose_name='Turi')),
                ('trigger_date', models.DateField(verbose_name='Qachon eslatish')),
                ('condition', models.CharField(choices=[('any', 'Shartsiz'), ('sunny', "Quyoshli / yomg'irsiz havo"), ('no_rain', "Yomg'ir yog'masa")], default='any', max_length=10, verbose_name='Shart')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('skipped', 'Shart bajarilmadi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=12, verbose_name='Holat')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
