# Generated by Django 6.0.4 on 2026-06-10 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='helper_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper2_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yordamchi ishchi 2'),
        ),
        migrations.AddField(
            model_name='order',
            name='helper_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper3_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yordamchi ishchi 3'),
        ),
    ]
