# Generated by Django 6.0.4 on 2026-06-10 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_helper_2_order_helper_3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Formula nomi')),
                ('category', models.CharField(choices=[('shampoo', 'Shampun (Yuvish)'), ('foam', "Faol ko'pik"), ('wax', 'Mum / Wax'), ('polish', 'Polirovka'), ('interior', 'Salon tozalovchi'), ('glass', 'Shisha tozalovchi'), ('tire', "Shina/g'ildirak parlatuvchi"), ('degreaser', "Yog' ketkazuvchi"), ('plastic', 'Plastik/rezina tiklovchi'), ('disinfect', 'Dezinfeksiyalovchi'), ('other', 'Boshqa')], default='shampoo', max_length=20, verbose_name='Turi')),
                ('purpose', models.TextField(help_text='Foydalanuvchi qanday natija kutgan', verbose_name='Maqsad / vazifa')),
                ('yield_volume', models.CharField(blank=True, help_text='Masalan, 10 litr tayyor mahsulot', max_length=50, verbose_name='Hosil hajmi')),
                ('ingredients', models.TextField(help_text='Komponentlar va miqdori', verbose_name='Tarkib')),
                ('instructions', models.TextField(verbose_name='Tayyorlash bosqichlari')),
                ('safety_notes', models.TextField(blank=True, verbose_name='Xavfsizlik eslatmalari')),
                ('usage_notes', models.TextField(blank=True, verbose_name="Qo'llash bo'yicha tavsiyalar")),
                ('ai_model', models.CharField(blank=True, max_length=60, verbose_name='Foydalanilgan AI model')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Sevimli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Kimyoviy formula',
                'verbose_name_plural': 'Kimyoviy formulalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
