# Generated by Django 6.0.4 on 2026-04-15 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[("light", "Yengil mashina"), ("heavy", "Yuk mashina")],
                        default="light",
                        max_length=10,
                        verbose_name="Mashina turi",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=50, verbose_name="Rusumi (Chevrolet, Nexia...)"
                    ),
                ),
                ("model", models.CharField(max_length=50, verbose_name="Modeli")),
                (
                    "plate_number",
                    models.CharField(max_length=15, verbose_name="Davlat raqami"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/",
                        verbose_name="Mashina rasmi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Egasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mashina",
                "verbose_name_plural": "Mashinalar",
                "ordering": ["-created_at"],
            },
        ),
    ]
