# Generated by Django 6.0.4 on 2026-04-24 03:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gas", "Gaz"),
                            ("water", "Suv"),
                            ("electricity", "Elektr"),
                            ("chemical", "Kimyoviy modda"),
                            ("foam", "Pena"),
                            ("spare_part", "Ehtiyot qism"),
                            ("tool", "Ish qurol"),
                            ("external", "Tashqi chiqim"),
                        ],
                        max_length=20,
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("communal", "Kommunal chiqimlar"),
                            ("raw", "Xom ashyo chiqimlari"),
                            ("external", "Tashqi chiqimlar"),
                        ],
                        max_length=20,
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="Izoh"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Miqdor (so'm)"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chiqim",
                "verbose_name_plural": "Chiqimlar",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("offline", "Oflayn xizmat"),
                            ("online", "Onlayn buyurtma (avtomatik)"),
                            ("extra", "Qo'shimcha xizmat"),
                        ],
                        max_length=20,
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Izoh / Xizmat nomi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Miqdor (so'm)"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incomes",
                        to="core.order",
                        verbose_name="Bog'liq buyurtma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kirim",
                "verbose_name_plural": "Kirimlar",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
