# Generated by Django 6.0.4 on 2026-04-15 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Sarlavha")),
                ("description", models.TextField(verbose_name="Tavsif / Tajriba")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("light", "Yengil mashina"),
                            ("heavy", "Yuk mashina"),
                            ("polish", "Polировka"),
                            ("interior", "Salon tozalash"),
                            ("full", "To'liq kompleks"),
                        ],
                        max_length=20,
                        verbose_name="Xizmat turi",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Narx (so'm)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.ForeignKey(
                        limit_choices_to={"role": "worker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ishchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat e'loni",
                "verbose_name_plural": "Xizmat e'lonlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
