# Generated by Django 6.0.4 on 2026-04-30 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Dushanba"),
                            (1, "Seshanba"),
                            (2, "Chorshanba"),
                            (3, "Payshanba"),
                            (4, "Juma"),
                            (5, "Shanba"),
                            (6, "Yakshanba"),
                        ],
                        verbose_name="Hafta kuni",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Boshlanish vaqti")),
                ("end_time", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ish kuni"),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ishchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish jadvali",
                "verbose_name_plural": "Ish jadvallari",
                "ordering": ["weekday"],
                "unique_together": {("worker", "weekday")},
            },
        ),
    ]
